/* Finance — mock data for the design prototype (SN-206). NOT business authority: every name/ID/number is fictional.
   FINANCE ROLE RUNTIME IS NOT LIVE VERIFIED (FIN-RUNTIME). Product boundaries: FINANCE-PRODUCT-SPEC.md + GATE-0-PRODUCT-INVARIANTS.md.
   Nothing here is saved, sent, posted or executed. Evidence ≠ approval ≠ fully paid ≠ entitlement ≠ wallet credit ≠ settlement. */
(function () {
  'use strict';
  var Q = function (o) {
    var d = { stage: [1, 1], purpose: 'پیش‌پرداخت', lk: 'ok', unit: 'toman', paid: 0, review: 'pending', prior: [], rev: 'بدون بازبین فعلی', next: 'مالی (بررسی)', invSt: 'در جریان وصول', refund: 'none', ledger: 'unposted', ent: 'none', facets: [], flags: [], fresh: 'now', valid: null };
    for (var k in o) d[k] = o[k]; d.rem = d.total - d.paid; return d;
  };
  var EV = function (k, ref, ver, by, at, src, amt) { return { k: k, ref: ref, ver: ver, by: by, at: at, src: src, amt: amt }; };
  var P = function (res, who, at, note) { return { res: res, who: who, at: at, note: note }; };

  var D = window.FIN = {
    user: { name: 'سارا مرادی', id: '۱۸۰۰۱', pos: 'مالی' },
    freshness: { now: '۱۴:۲۰', evaluated: 'امروز ۱۴:۲۰ (+۰۳:۳۰)', stale: 'دیروز ۱۸:۱۰' },
    /* ---------- Review Queue: grain = one reviewable payment stage / evidence context linked to an invoice ---------- */
    queue: [
      Q({ id: 'RS-2101', inv: 'INV-48213', stage: [1, 3], purpose: 'پیش‌پرداخت', cs: 'CASE-7731', src: 'فروش تلفنی', cust: 'مشتری ۷۷۳۱', seller: 'مریم احمدی', team: 'شمال ۱', ev: EV('receipt', 'EV-9921', 'v2', 'فروشنده', 'امروز ۰۹:۱۲', 'بارگذاری فروشنده', 12000000), claimed: 12000000, total: 36000000, facets: ['needs', 'receipt'] }),
      Q({ id: 'RS-2102', inv: 'INV-48190', stage: [2, 3], purpose: 'قسط دوم', cs: 'CASE-7702', src: 'فروش تلفنی', cust: 'مشتری ۷۷۰۲', seller: 'زهرا کریمی', team: 'شمال ۱', ev: EV('receipt', 'EV-9907', 'v1', 'فروشنده', 'امروز ۰۸:۳۰', 'بارگذاری فروشنده', 10000000), claimed: 10000000, total: 30000000, paid: 10000000, prior: [P('approved', 'سارا مرادی', '۱۴۰۵/۰۷/۰۸', 'مرحله ۱ تأیید شد')], facets: ['needs', 'receipt'] }),
      Q({ id: 'RS-2103', inv: 'INV-48177', stage: [1, 1], purpose: 'پرداخت کامل', cs: 'CASE-7689', src: 'سفارش وب‌سایت', cust: 'مشتری ۷۶۸۹', seller: 'رضا پاکزاد', team: 'جنوب ۲', ev: EV('gateway', 'ZB-55012', 'v1', 'درگاه', 'امروز ۰۷:۴۵', 'ثبت درگاه (Zibal)', 8500000), claimed: 8500000, total: 8500000, facets: ['needs', 'online'], flags: ['gatewayOnly'] }),
      Q({ id: 'RS-2104', inv: 'INV-48201', stage: [1, 2], purpose: 'پیش‌پرداخت', cs: 'CASE-7715', src: 'فروش تلفنی', cust: 'مشتری ۷۷۱۵', seller: 'مریم احمدی', team: 'شمال ۱', ev: null, claimed: 5000000, total: 10000000, facets: ['needs'], flags: ['noEvidence'] }),
      Q({ id: 'RS-2105', inv: 'INV-48155', stage: [1, 2], purpose: 'پیش‌پرداخت', cs: 'CASE-7660', src: 'فروش تلفنی', cust: 'مشتری ۷۶۶۰', seller: 'نیما رحیمی', team: 'جنوب ۲', ev: EV('receipt', 'EV-9890', 'v1', 'فروشنده', 'دیروز ۱۶:۰۵', 'بارگذاری فروشنده', 14500000), claimed: 15000000, total: 30000000, facets: ['needs', 'receipt'], flags: ['mismatch'] }),
      Q({ id: 'RS-2106', inv: 'INV-48144', stage: [2, 2], purpose: 'تسویه نهایی', cs: 'CASE-7644', src: 'فروش تلفنی', cust: 'مشتری ۷۶۴۴', seller: 'زهرا کریمی', team: 'شمال ۱', ev: EV('receipt', 'EV-9876', 'v1', 'فروشنده', 'دیروز ۱۱:۲۰', 'بارگذاری فروشنده', 9000000), claimed: 9000000, total: 18000000, paid: 9000000, prior: [P('approved', 'سارا مرادی', '۱۴۰۵/۰۷/۰۳', 'مرحله ۱ تأیید شد')], facets: ['needs', 'receipt'], stale: { by: 'امیر صادقی', at: '۱۰ دقیقه پیش', res: 'approved' } }),
      Q({ id: 'RS-2107', inv: 'INV-48139', stage: [1, 1], purpose: 'پرداخت کامل', cs: 'CASE-7640', src: 'فروش تلفنی', cust: 'مشتری ۷۶۴۰', seller: 'رضا پاکزاد', team: 'جنوب ۲', ev: EV('receipt', 'EV-9871', 'v1', 'فروشنده', 'دیروز ۰۹:۵۰', 'بارگذاری فروشنده', 120000), claimed: 120000, unit: null, total: 120000, facets: ['needs', 'receipt'], flags: ['unit'] }),
      Q({ id: 'RS-2108', inv: 'INV-48120', stage: [1, 2], purpose: 'پیش‌پرداخت', cs: 'CASE-7622', src: 'سفارش وب‌سایت', cust: 'مشتری ۷۶۲۲', seller: 'نیما رحیمی', team: 'جنوب ۲', ev: EV('receipt', 'EV-9880', 'v1', 'فروشنده', 'دیروز ۱۰:۱۰', 'بارگذاری فروشنده', 7000000), claimed: 7000000, total: 14000000, facets: ['needs', 'receipt'], flags: ['dup'], dupOf: 'EV-9870 (فاکتور INV-48098، شماره پیگیری بانکی مشترک)' }),
      Q({ id: 'RS-2109', inv: 'INV-48101', stage: [1, 2], purpose: 'پیش‌پرداخت', cs: 'CASE-7601', src: 'فروش تلفنی', cust: 'مشتری ۷۶۰۱', seller: 'مریم احمدی', team: 'شمال ۱', ev: EV('receipt', 'EV-9801', 'v1', 'فروشنده', '۱۴۰۵/۰۷/۱۳', 'بارگذاری فروشنده', 4000000), claimed: 6000000, total: 12000000, review: 'rejected', prior: [P('rejected', 'سارا مرادی', '۱۴۰۵/۰۷/۱۴', 'رسید نامرتبط با این فاکتور؛ مبلغ مندرج با ادعا نمی‌خواند')], rev: 'سارا مرادی', next: 'فروشنده (اصلاح و ارسال دوباره)', facets: ['rejected'], retSeller: true }),
      Q({ id: 'RS-2110', inv: 'INV-48090', stage: [3, 3], purpose: 'تسویه نهایی', cs: 'CASE-7590', src: 'فروش تلفنی', cust: 'مشتری ۷۵۹۰', seller: 'زهرا کریمی', team: 'شمال ۱', ev: EV('receipt', 'EV-9788', 'v1', 'فروشنده', '۱۴۰۵/۰۷/۱۰', 'بارگذاری فروشنده', 12000000), claimed: 12000000, valid: 12000000, total: 36000000, paid: 36000000, review: 'approved', prior: [P('approved', 'سارا مرادی', '۱۴۰۵/۰۷/۱۱', 'مرحله ۳ تأیید شد')], rev: 'سارا مرادی', next: 'مسیر سفارش (گام بعد)', invSt: 'پرداخت کامل (طبق مبلغ معتبر)', ledger: 'unknown', ent: 'earned', facets: ['approved', 'receipt'] }),
      Q({ id: 'RS-2111', inv: 'INV-48088', stage: [1, 2], purpose: 'پیش‌پرداخت', cs: null, lk: 'unknown', src: 'نامعلوم', cust: 'نامشخص', seller: 'مریم احمدی', team: 'شمال ۱', ev: EV('receipt', 'EV-9795', 'v1', 'فروشنده', 'دیروز ۱۵:۴۰', 'بارگذاری فروشنده', 7000000), claimed: 7000000, total: 14000000, facets: ['needs', 'receipt'], flags: ['link'] }),
      Q({ id: 'RS-2112', inv: 'INV-48075', stage: [1, 2], purpose: 'پیش‌پرداخت', cs: 'CASE-7555', src: 'فروش تلفنی', cust: 'مشتری ۷۵۵۵', seller: 'نیما رحیمی', team: 'جنوب ۲', ev: EV('receipt', 'EV-9770', 'v1', 'فروشنده', 'امروز ۱۰:۰۲', 'بارگذاری فروشنده', 6000000), claimed: 6000000, total: 12000000, facets: ['needs', 'receipt'] }),
      Q({ id: 'RS-2113', inv: 'INV-48070', stage: [2, 2], purpose: 'تسویه نهایی', cs: 'CASE-7549', src: 'فروش تلفنی', cust: 'مشتری ۷۵۴۹', seller: 'رضا پاکزاد', team: 'جنوب ۲', ev: EV('receipt', 'EV-9766', 'v1', 'فروشنده', 'امروز ۱۰:۲۰', 'بارگذاری فروشنده', 5000000), claimed: 5000000, total: 10000000, paid: 5000000, prior: [P('approved', 'امیر صادقی', '۱۴۰۵/۰۷/۰۲', 'مرحله ۱ تأیید شد')], facets: ['needs', 'receipt'], bulkOutcome: 'unknown' }),
      Q({ id: 'RS-2114', inv: 'INV-48075', stage: [2, 2], purpose: 'تسویه نهایی', cs: 'CASE-7555', src: 'فروش تلفنی', cust: 'مشتری ۷۵۵۵', seller: 'نیما رحیمی', team: 'جنوب ۲', ev: EV('receipt', 'EV-9760', 'v1', 'فروشنده', 'امروز ۱۰:۴۱', 'بارگذاری فروشنده', 6000000), claimed: 6000000, total: 12000000, facets: ['needs', 'receipt'], bulkOutcome: 'failed' })
    ],
    /* ---------- Refund (CONDITIONAL — OPD-04 unresolved). States: requested · reported · proof_pending · confirmed · partial · full · unknown ---------- */
    refunds: [
      { id: 'RF-31', inv: 'INV-48010', st: 'requested', paidOrig: 20000000, req: 20000000, done: 0, unit: 'toman', exec: 'نامشخص', proof: null, rev: 'بدون بازبین', hist: ['درخواست توسط فروش ثبت شد'], invCancelled: true, note: 'فاکتور لغو شده است؛ لغو فاکتور به‌معنی بازگشت وجه نیست.' },
      { id: 'RF-32', inv: 'INV-47980', st: 'proof_pending', paidOrig: 18000000, req: 5000000, done: 5000000, unit: 'toman', exec: 'ادعای گزارش‌شده (دستی)', proof: null, rev: 'سارا مرادی', hist: ['درخواست ثبت شد', 'اجرای استرداد گزارش شد (ادعایی)'], note: 'مدرک اجرا هنوز ارائه نشده؛ مبلغ «گزارش‌شده» است نه «تأییدشده».' },
      { id: 'RF-33', inv: 'INV-47950', st: 'partial', paidOrig: 12000000, req: 4000000, done: 4000000, unit: 'toman', exec: 'بانک (دستی)', proof: 'مرجع BNK-77412 · ۱۴۰۵/۰۷/۰۹', rev: 'امیر صادقی', hist: ['درخواست ثبت شد', 'اجرا گزارش شد', 'مدرک ثبت و بررسی شد'], note: 'نوع مدرک بانکی و تأییدکنندهٔ مجاز تعریف‌شده نیست (OPD-04)؛ «تأییدشده» در اینجا فقط ثبت بررسی است.' },
      { id: 'RF-34', inv: 'INV-47920', st: 'unknown', paidOrig: 9000000, req: 9000000, done: null, unit: 'toman', exec: 'درگاه', proof: null, rev: 'بدون بازبین', hist: ['درخواست ثبت شد', 'پاسخ اجرا نرسید'], note: 'نتیجه اجرا نامعلوم است؛ تکرار پولی خودکار ممنوع تا تطبیق.' }
    ],
    /* ---------- Ledger: two independent domains (never one balance without basis). state: committed · preview · unknown ---------- */
    ledger: [
      { id: 'T-9001', key: 'INV-48190|S1|collection', dom: 'collection', acct: 'وصول فاکتور', dir: 'C', amt: 10000000, unit: 'toman', rel: ['فاکتور', 'INV-48190 · مرحله ۱'], actor: 'سیستم (تأیید مرحله)', eff: '۱۴۰۵/۰۷/۰۸', posted: '۱۴۰۵/۰۷/۰۸ ۱۱:۰۲', st: 'committed' },
      { id: 'T-9002', key: 'INV-48190|S1|purpose:sales|role:seller|rec:HP-302', dom: 'wallet', acct: 'کیف پول کمیسیون · زهرا کریمی', dir: 'C', amt: 1200000, unit: 'toman', rel: ['موتور هدف‌دار', 'INV-48190 · مرحله ۱'], actor: 'سیستم (موتور هدف‌دار)', eff: '۱۴۰۵/۰۷/۰۸', posted: '۱۴۰۵/۰۷/۰۸ ۱۱:۰۲', st: 'committed' },
      { id: 'T-9003', key: 'INV-48190|S1|purpose:sales|role:sup|rec:HP-210', dom: 'wallet', acct: 'کیف پول کمیسیون · آرش یگانه', dir: 'C', amt: 900000, unit: 'toman', rel: ['موتور هدف‌دار', 'INV-48190 · مرحله ۱'], actor: 'سیستم (موتور هدف‌دار)', eff: '۱۴۰۵/۰۷/۰۸', posted: '۱۴۰۵/۰۷/۰۸ ۱۱:۰۲', st: 'committed' },
      { id: 'T-9004', key: 'RUN-308|INV-48033|S1|rec:HP-301', dom: 'wallet', acct: 'کیف پول کمیسیون · مریم احمدی', dir: 'C', amt: 1500000, unit: 'toman', rel: ['اجرا', 'RUN-308 · INV-48033'], actor: 'سارا مرادی (ثبت اجرا)', eff: '۱۴۰۵/۰۶/۲۸', posted: '۱۴۰۵/۰۶/۲۹ ۰۹:۴۰', st: 'committed', revs: ['T-9005', 'T-9006'] },
      { id: 'T-9005', key: 'REV|T-9004', dom: 'wallet', acct: 'کیف پول کمیسیون · مریم احمدی', dir: 'D', amt: 1500000, unit: 'toman', rel: ['معکوس‌سازی', 'T-9004 · لغو فاکتور INV-48033'], actor: 'سیستم (معکوس‌سازی لغو)', eff: '۱۴۰۵/۰۷/۰۲', posted: '۱۴۰۵/۰۷/۰۲ ۱۶:۱۵', st: 'committed', of: 'T-9004', why: 'لغو فاکتور؛ رویداد جبرانی مرتبط، نه حذف رویداد اصلی' },
      { id: 'T-9006', key: 'COR|T-9004|rec:HP-303', dom: 'wallet', acct: 'کیف پول کمیسیون · کامران زارع', dir: 'C', amt: 1500000, unit: 'toman', rel: ['اصلاح', 'T-9004 · گیرندهٔ درست'], actor: 'امیر صادقی (اصلاح مجاز)', eff: '۱۴۰۵/۰۷/۰۳', posted: '۱۴۰۵/۰۷/۰۳ ۱۰:۰۵', st: 'committed', of: 'T-9004', why: 'اصلاح گیرنده با رویداد جدید مرتبط' },
      { id: 'T-9007', key: 'RF-33|INV-47950|refund', dom: 'collection', acct: 'وصول فاکتور (استرداد)', dir: 'D', amt: 4000000, unit: 'toman', rel: ['استرداد', 'RF-33 · INV-47950'], actor: 'امیر صادقی', eff: '۱۴۰۵/۰۷/۰۹', posted: '۱۴۰۵/۰۷/۰۹ ۱۷:۲۰', st: 'committed' },
      { id: '—', key: 'RUN-305|INV-48012|S1|rec:HP-301', dom: 'wallet', acct: 'کیف پول کمیسیون · مریم احمدی', dir: 'C', amt: 1100000, unit: 'toman', rel: ['اجرا', 'RUN-305 · INV-48012'], actor: 'سارا مرادی (ثبت اجرا)', eff: '—', posted: 'نامعلوم', st: 'unknown', note: 'پاسخ ثبت نرسید؛ ممکن است ثبت شده باشد. ثبت‌شده فرض نمی‌شود و «صفر» هم نیست.' },
      { id: '—', key: 'RUN-311|INV-48222|S1|rec:HP-302', dom: 'wallet', acct: 'کیف پول کمیسیون · زهرا کریمی', dir: 'C', amt: 800000, unit: 'toman', rel: ['اجرا (پیش‌نمایش)', 'RUN-311 · INV-48222'], actor: '—', eff: '—', posted: 'ثبت نشده', st: 'preview', note: 'فقط محاسبه پیش‌نمایش؛ تراکنش نیست.' },
      { id: 'T-9011', key: 'INV-47001|S1|collection', dom: 'collection', acct: 'وصول فاکتور', dir: 'C', amt: 250000000, unit: 'rial', rel: ['فاکتور', 'INV-47001 · مرحله ۱'], actor: 'سیستم (تأیید مرحله)', eff: '۱۴۰۵/۰۵/۱۲', posted: '۱۴۰۵/۰۵/۱۲ ۱۲:۱۰', st: 'committed' },
      { id: 'T-9012', key: '(کلید ثبت نشده)', dom: 'wallet', acct: 'کیف پول کمیسیون · نامشخص', dir: 'C', amt: 600000, unit: 'toman', rel: ['بدون رابطه قابل اثبات', '—'], actor: 'نامشخص', eff: '—', posted: '۱۴۰۵/۰۴/۰۱ ۰۸:۰۰', st: 'committed', orphan: true, note: 'شبه‌یتیم: رابطه با فاکتور اثبات نشده؛ حذف یا اتصال حدسی (مثلاً با شماره تلفن) ممنوع است.' }
    ],
    /* ---------- Runs: Draft · Preview · Approved · Posting · Posted · Partial · Failed · Outcome Unknown · Reconciled ---------- */
    runs: [
      { id: 'RUN-312', st: 'draft', eng: 'purpose', engL: 'موتور هدف‌دار', name: 'محاسبه کمیسیون پیش‌پرداخت (پیش‌نویس)', by: 'سارا مرادی', at: 'امروز ۱۳:۵۰', intended: null, items: [], note: 'نیت محاسبه است؛ هنوز ردیف مالی یا پیش‌نمایش ساخته نشده است.' },
      { id: 'RUN-311', st: 'preview', eng: 'legacy', engL: 'اجرای قدیمی (run/APPLY)', name: 'کمیسیون مهر ۱۴۰۵ — پیش‌نمایش', by: 'سارا مرادی', at: 'امروز ۰۹:۴۰', intended: 48, cov: { intended: 48, processed: 0, posted: 0, existing: 0, failed: 0, unprocessed: 48, unknown: 0 }, sim: 'ok', items: [['INV-48222 · مرحله ۱ · فروشنده', 'RUN-311|INV-48222|S1|rec:HP-302', 800000, 'toman', 'notposted', null, ''], ['INV-48222 · مرحله ۱ · سرپرست', 'RUN-311|INV-48222|S1|rec:HP-210', 600000, 'toman', 'notposted', null, '']], note: 'تولید پیش‌نمایش خودش نوشتن فراداده (اجرا/ردیف) است؛ خواندن خالص نیست.' },
      { id: 'RUN-309', st: 'approved', eng: 'legacy', engL: 'اجرای قدیمی (run/APPLY)', name: 'کمیسیون شهریور ۱۴۰۵ — تأییدشده', by: 'سارا مرادی', at: '۱۴۰۵/۰۷/۱۴', intended: 86, cov: { intended: 86, processed: 0, posted: 0, existing: 0, failed: 0, unprocessed: 86, unknown: 0 }, appr: { by: 'امیر صادقی', at: '۱۴۰۵/۰۷/۱۵ ۱۰:۱۰', locked: '۱۴۰۵/۰۷/۱۵ ۱۰:۱۰' }, sim: 'unknown', items: [['INV-48180 · مرحله ۱ · فروشنده', 'RUN-309|INV-48180|S1|rec:HP-301', 1100000, 'toman', 'notposted', null, ''], ['INV-48180 · مرحله ۱ · سرپرست', 'RUN-309|INV-48180|S1|rec:HP-210', 800000, 'toman', 'notposted', null, '']], note: 'تأیید ≠ ثبت در کیف پول. ثبت فقط با اجرای جدا و مجاز انجام می‌شود.' },
      { id: 'RUN-308', st: 'posted', eng: 'legacy', engL: 'اجرای قدیمی (run/APPLY)', name: 'کمیسیون مرداد ۱۴۰۵', by: 'سارا مرادی', at: '۱۴۰۵/۰۶/۲۹', intended: 52, cov: { intended: 52, processed: 52, posted: 49, existing: 3, failed: 0, unprocessed: 0, unknown: 0 }, appr: { by: 'امیر صادقی', at: '۱۴۰۵/۰۶/۲۸', locked: '۱۴۰۵/۰۶/۲۸' }, items: [['INV-48033 · مرحله ۱ · فروشنده', 'RUN-308|INV-48033|S1|rec:HP-301', 1500000, 'toman', 'posted', 'T-9004', 'بعداً معکوس و اصلاح شد'], ['INV-48010 · مرحله ۱ · فروشنده', 'RUN-308|INV-48010|S1|rec:HP-302', 900000, 'toman', 'existing', 'T-8890', 'تراکنش موجود یافت شد؛ اعتبار جدید ساخته نشد']], note: 'پوشش کامل با شناسه تراکنش هر آیتم اثبات شده است.' },
      { id: 'RUN-307', st: 'partial', eng: 'legacy', engL: 'اجرای قدیمی (run/APPLY)', name: 'کمیسیون تیر ۱۴۰۵ (حجم بالا)', by: 'سارا مرادی', at: '۱۴۰۵/۰۵/۱۸', intended: 2340, cov: { intended: 2340, processed: 2000, posted: 1874, existing: 112, failed: 14, unprocessed: 340, unknown: 0 }, appr: { by: 'امیر صادقی', at: '۱۴۰۵/۰۵/۱۷', locked: '۱۴۰۵/۰۵/۱۷' }, sim: 'tail', items: [['INV-47310 · مرحله ۱ · فروشنده', 'RUN-307|INV-47310|S1|rec:HP-301', 700000, 'toman', 'failed', null, 'خطا: گیرنده معتبر نیست'], ['INV-47955 · مرحله ۲ · فروشنده', 'RUN-307|INV-47955|S2|rec:HP-302', 650000, 'toman', 'unprocessed', null, 'بعد از سقف ۲۰۰۰ آیتم هر فراخوانی'], ['INV-47956 · مرحله ۱ · سرپرست', 'RUN-307|INV-47956|S1|rec:HP-210', 480000, 'toman', 'unprocessed', null, 'بعد از سقف ۲۰۰۰ آیتم هر فراخوانی']], note: 'بخشی از آیتم‌ها ثبت شد؛ دنبالهٔ پردازش‌نشده و آیتم‌های ناموفق جدا شمرده می‌شوند (FIN-RUN-COVERAGE).' },
      { id: 'RUN-306', st: 'failed', eng: 'legacy', engL: 'اجرای قدیمی (run/APPLY)', name: 'کمیسیون خرداد ۱۴۰۵', by: 'سارا مرادی', at: '۱۴۰۵/۰۴/۲۹', intended: 30, cov: { intended: 30, processed: 30, posted: 0, existing: 0, failed: 30, unprocessed: 0, unknown: 0 }, appr: { by: 'امیر صادقی', at: '۱۴۰۵/۰۴/۲۸', locked: '۱۴۰۵/۰۴/۲۸' }, items: [['INV-46880 · مرحله ۱ · فروشنده', 'RUN-306|INV-46880|S1|rec:HP-301', 900000, 'toman', 'failed', null, 'پرچم ثبت غیرفعال بود؛ پیش از نوشتن رد شد']], proofZero: true, note: 'شکست معلوم؛ اثر صفر با جستجوی کلید تک‌تک آیتم‌ها اثبات شده است.' },
      { id: 'RUN-305', st: 'unknown', eng: 'legacy', engL: 'اجرای قدیمی (run/APPLY)', name: 'کمیسیون اردیبهشت ۱۴۰۵', by: 'سارا مرادی', at: 'دیروز ۱۷:۳۰', intended: 120, cov: { intended: 120, processed: null, posted: null, existing: null, failed: null, unprocessed: null, unknown: 120 }, appr: { by: 'امیر صادقی', at: 'دیروز ۱۷:۰۰', locked: 'دیروز ۱۷:۰۰' }, sim: 'recon', lookup: { committed: 70, notCommitted: 50, byKey: { 'RUN-305|INV-48012|S1|rec:HP-301': 'committed' }, txByKey: { 'RUN-305|INV-48012|S1|rec:HP-301': 'T-8801' } }, items: [['INV-48012 · مرحله ۱ · فروشنده', 'RUN-305|INV-48012|S1|rec:HP-301', 1100000, 'toman', 'unknown', null, 'پاسخ نرسید']], note: 'اتصال پیش از دریافت پاسخ قطع شد؛ ممکن است بخشی یا همه ثبت شده باشد.' },
      { id: 'RUN-304', st: 'reconciled', eng: 'legacy', engL: 'اجرای قدیمی (run/APPLY)', name: 'کمیسیون فروردین ۱۴۰۵', by: 'سارا مرادی', at: '۱۴۰۵/۰۳/۳۱', intended: 64, cov: { intended: 64, processed: 64, posted: 60, existing: 4, failed: 0, unprocessed: 0, unknown: 0 }, appr: { by: 'امیر صادقی', at: '۱۴۰۵/۰۳/۳۰', locked: '۱۴۰۵/۰۳/۳۰' }, items: [['INV-46010 · مرحله ۱ · فروشنده', 'RUN-304|INV-46010|S1|rec:HP-301', 700000, 'toman', 'posted', 'T-8120', 'در تطبیق: ثبت‌شده بود']], note: 'پیش‌تر «نامعلوم» بود؛ با جستجوی تراکنش/کلید هر آیتم تطبیق شد. تکرار کور انجام نشد.' }
    ],
    rules: [
      { id: 'RL-1', purpose: 'فروش · پیش‌پرداخت', eng: 'موتور هدف‌دار', from: '۱۴۰۵/۰۱/۰۱', on: true, src: 'جبران خدمات مؤثر (منابع انسانی)' },
      { id: 'RL-2', purpose: 'فروش · تسویه نهایی', eng: 'موتور هدف‌دار', from: '۱۴۰۵/۰۱/۰۱', on: true, src: 'جبران خدمات مؤثر (منابع انسانی)' },
      { id: 'RL-3', purpose: 'اجرای قدیمی ماهانه', eng: 'اجرای قدیمی', from: '۱۴۰۴/۰۱/۰۱', on: true, src: 'قاعدهٔ اجرا (قدیمی)' },
      { id: 'RL-4', purpose: 'غیرفاکتور (مسیر نامشخص)', eng: 'نامشخص (OPD-09)', from: '—', on: false, src: 'تعریف نشده' }
    ],
    /* ---------- Reconciliation issues (10 supported categories). No Fix All. ---------- */
    issues: [
      { id: 'I-1', cls: 'amount', title: 'اختلاف مبلغ: ادعا ۱۵٬۰۰۰٬۰۰۰ — مدرک ۱۴٬۵۰۰٬۰۰۰', ent: ['stage', 'RS-2105', 'INV-48155'], ev: ['مدرک EV-9890 v1', 'مبلغ ادعا‌شده در مرحله', 'مجموع فاکتور ۳۰٬۰۰۰٬۰۰۰'], impact: 'تأیید با مبلغ نادرست مقدار وصول معتبر را تغییر می‌دهد و ممکن است اعتبار خودکار بسازد.', owner: 'مالی؛ منبع اختلاف: فروش/MIS', allowed: ['روشن‌سازی با فروشنده', 'رد با دلیل یا تأیید با اصلاح مبلغ مجاز'], restricted: ['بازنویسی مجموع/تاریخچه برای حذف اختلاف'], next: 'فروشنده (اصلاح یا توضیح)', proof: 'مبلغ/واحد/مبنا یکسان + دلیل ثبت‌شده', conf: 'ok', state: 'open', sev: 'orange' },
      { id: 'I-2', cls: 'dup', title: 'پرداخت تکراری احتمالی (شماره پیگیری بانکی مشترک)', ent: ['stage', 'RS-2108', 'INV-48120 ↔ INV-48098'], ev: ['EV-9880 و EV-9870 با یک مرجع بانکی'], impact: 'اعتبار دوباره یا وصول مضاعف.', owner: 'مالی', allowed: ['بررسی مراجع', 'علامت‌گذاری مورد اختلافی', 'معکوس‌سازی مجاز طبق سیاست'], restricted: ['حذف پرداخت', 'اعتبار خودکار برای هر دو'], next: 'مالی (بررسی تکراری)', proof: 'مراجع پرداخت یکتا و نتیجهٔ مالی', conf: 'conflict', state: 'open', sev: 'red' },
      { id: 'I-3', cls: 'mirror', title: 'نبود آینهٔ فاکتور برای پرداخت درگاهی', ent: ['payment', 'ZB-55090', '—'], ev: ['رکورد درگاه بدون فاکتور CRM مرتبط'], impact: 'وصول واقعی بدون فاکتور؛ ممکن است در گزارش‌ها دیده نشود.', owner: 'MIS (فنی) · مالی بررسی اثر', allowed: ['ارجاع شواهد به MIS', 'بررسی اثر مالی'], restricted: ['ساخت یا اتصال حدسی فاکتور'], next: 'MIS (منبع/آینه)', proof: 'مراجع پایدار منبع و فاکتور + برابری', conf: 'unknown', state: 'awaiting', sev: 'amber' },
      { id: 'I-4', cls: 'stage', title: 'ناهمخوانی مرحله و بررسی: مرحله ۲ تأییدشده، مرحله ۱ در انتظار', ent: ['stage', 'RS-2106', 'INV-48144'], ev: ['تاریخچه مرحله', 'تصمیم‌های قبلی'], impact: 'ترتیب منطقی وصول به هم می‌خورد؛ وضعیت فاکتور قابل اتکا نیست.', owner: 'مالی', allowed: ['بازبینی مرحلهٔ فعال و رد تصمیم‌ها'], restricted: ['بازنشانی تأییدهای قبلی'], next: 'مالی', proof: 'مرحلهٔ فعال و اثر تصمیم‌ها', conf: 'ok', state: 'open', sev: 'orange' },
      { id: 'I-5', cls: 'report', title: 'عدم تطابق گزارش وصول با وضعیت فاکتورها', ent: ['report', 'REP-CUR', 'گزارش وضعیت فعلی'], ev: ['جمع گزارش ۴۱٬۲۰۰٬۰۰۰ — جمع فاکتورها ۴۰٬۰۰۰٬۰۰۰ (همان بازه)'], impact: 'تصمیم‌گیری روی عدد نادرست.', owner: 'MIS (پرس‌وجو) · مالی (معنای مالی)', allowed: ['تشخیص با MIS', 'تأیید معنای مالی'], restricted: ['بازنویسی رکورد مالی به‌خاطر جمع جدول'], next: 'MIS', proof: 'واحد/بازه/منبع/زمان یکسان و برابری', conf: 'ok', state: 'awaiting', sev: 'amber' },
      { id: 'I-6', cls: 'refund', title: 'فاکتور لغو‌شده بدون مدرک بازگشت وجه', ent: ['refund', 'RF-31', 'INV-48010'], ev: ['وضعیت لغو', 'پرداخت اولیه ۲۰٬۰۰۰٬۰۰۰'], impact: 'مشتری ممکن است وجه خود را دریافت نکرده باشد؛ لغو ≠ استرداد.', owner: 'مالی؛ مدرک: ارائه‌دهندهٔ اجرا', allowed: ['درخواست مدرک', 'بررسی مرجع'], restricted: ['فرض لغو = استرداد', 'اجرای بانکی از این رابط'], next: 'ارائه‌دهندهٔ مدرک / مالی', proof: 'مراجع پرداخت و استرداد اولیه + اثر خالص', conf: 'ok', state: 'open', sev: 'orange' },
      { id: 'I-7', cls: 'ledger', title: 'تراکنش جبرانی بدون ارتباط روشن با رویداد اصلی', ent: ['tx', 'T-9006', 'T-9004'], ev: ['T-9004 → T-9005 → T-9006'], impact: 'مانده دامنه با مبنا قابل توضیح نیست.', owner: 'مالی؛ مهندسی (مشروط)', allowed: ['اصلاح مرتبط مجاز'], restricted: ['بازنویسی مانده/حذف'], next: 'مالی', proof: 'توالی تراکنش و منشأ مانده', conf: 'ok', state: 'open', sev: 'amber' },
      { id: 'I-8', cls: 'unknown', title: 'نتیجه ثبت اجرای RUN-305 نامعلوم است', ent: ['run', 'RUN-305', '۱۲۰ آیتم'], ev: ['پاسخ ثبت نرسید'], impact: 'ممکن است بخشی اعتبار ثبت شده باشد؛ تکرار کور = ثبت مضاعف.', owner: 'مالی + تشخیص فنی', allowed: ['جستجوی تراکنش/کلید (فقط خواندنی)', 'طبقه‌بندی ثبت‌شده/ثبت‌نشده'], restricted: ['تکرار کور', 'خطا = اثر صفر'], next: 'مالی', proof: 'شناسهٔ تراکنش‌ها و پوشش هر آیتم', conf: 'ok', state: 'open', sev: 'red' },
      { id: 'I-9', cls: 'unit', title: 'ابهام واحد: ۱۲۰٬۰۰۰ تومان یا ریال؟', ent: ['stage', 'RS-2107', 'INV-48139'], ev: ['EV-9871 بدون واحد روشن'], impact: 'خطای ×۱۰ در وصول و کمیسیون.', owner: 'مالک سیاست مالی (OPD-06)', allowed: ['اخذ واحد و تبدیل مصوب'], restricted: ['حدس ×۱۰ یا گرد کردن'], next: 'مالک سیاست', proof: 'قرارداد مصوب OPD-06 و واحد منبع', conf: 'unknown', state: 'awaiting', sev: 'amber' },
      { id: 'I-10', cls: 'orphan', title: 'تراکنش شبه‌یتیم کیف پول', ent: ['tx', 'T-9012', '—'], ev: ['کلید ثبت نشده', 'بدون فاکتور قابل اثبات'], impact: 'مانده بدون منشأ؛ خطر اتصال حدسی.', owner: 'MIS (تبار) · مالی (محافظت)', allowed: ['حفظ', 'ارجاع برای اثبات'], restricted: ['اتصال با شماره تلفن', 'حذف'], next: 'MIS (تبار)', proof: 'Case/منبع/فاکتور/تراکنش اثبات‌شده', conf: 'unknown', state: 'awaiting', sev: 'amber' }
    ],
    reports: [
      { id: 'REP-WL', name: 'بار کاری بررسی', grain: 'مرحلهٔ قابل بررسی', basis: 'snap', time: 'زمان ارسال/بررسی', unit: 'تعداد، سن (ساعت)', src: 'صف بررسی', fresh: 'ok', cov: 'ok', rec: 'facetهای هم‌پوشان جمع نمی‌شوند', rows: [['در انتظار بررسی', '۱۰ مرحله'], ['رسید بارگذاری‌شده', '۱۰ مرحله (هم‌پوشان با بالا)'], ['ثبت درگاهی', '۱ مرحله (هم‌پوشان)']], export: 'محدود به شواهد حداقلی' },
      { id: 'REP-CUR', name: 'وضعیت مالی فعلی فاکتور', grain: 'فاکتور', basis: 'snap', time: 'لحظهٔ اسنپ‌شات', unit: 'تومان و ریال جدا', src: 'فاکتور/پرداخت/مرحله', fresh: 'ok', cov: 'ok', rec: 'عدم تطابق باز (I-5)', rows: [['کل / وصول‌شده / باقی‌مانده — تومان', '۲۳۶٬۰۰۰٬۰۰۰ / ۶۱٬۰۰۰٬۰۰۰ / ۱۷۵٬۰۰۰٬۰۰۰'], ['فاکتور با واحد نامشخص', '۱ (جدا؛ در جمع نیست)'], ['کل / وصول‌شده — ریال', '۲۵۰٬۰۰۰٬۰۰۰ / ۲۵۰٬۰۰۰٬۰۰۰ (جدا از تومان)']], export: 'همان فیلتر و grain؛ همه ردیف‌ها یا فقط صفحه مشخص شود' },
      { id: 'REP-TX', name: 'رویدادهای تراکنش (پرداخت/استرداد)', grain: 'رویداد پرداخت/استرداد', basis: 'range', time: 'زمان رویداد', unit: 'ناخالص / استرداد / خالص (تومان)', src: 'درگاه + محلی', fresh: 'ok', cov: 'partial', rec: 'بدون توکن، fallback محلی ممکن است', rows: [['ناخالص', '۴۱٬۲۰۰٬۰۰۰'], ['استرداد', '۴٬۰۰۰٬۰۰۰'], ['خالص', '۳۷٬۲۰۰٬۰۰۰']], export: 'منبع API یا fallback محلی اعلام شود', note: 'CSV درگاه ممکن است fallback محلی و ستون‌های خالی Zibal داشته باشد؛ «کل تراکنش‌های درگاه» اثبات‌شده نیست.' },
      { id: 'REP-LG', name: 'فعالیت دفتر کل', grain: 'تراکنش', basis: 'range', time: 'زمان اثر مالی در برابر زمان ثبت', unit: 'به تفکیک دامنه و واحد', src: 'تراکنش‌های ثبت‌شده', fresh: 'ok', cov: 'ok', rec: 'تراکنش نامعلوم و پیش‌نمایش جدا', rows: [['کیف پول کمیسیون (تومان) — ثبت‌شده', '۴ تراکنش'], ['وصول فاکتور (تومان)', '۲ تراکنش'], ['نامعلوم/پیش‌نمایش', '۲ مورد (در تراکنش‌ها نیست)']], export: 'فیلدهای محدود دفتر کل' },
      { id: 'REP-RN', name: 'اجراها و ثبت', grain: 'اجرا / آیتم', basis: 'snap', time: 'زمان تولید/بررسی/ثبت', unit: 'تعداد آیتم', src: 'snapshot + شناسه تراکنش', fresh: 'ok', cov: 'bounded', rec: 'زیرمجموعه ≠ خروجی کامل', rows: [['RUN-307 پردازش‌شده / کل', '۲٬۰۰۰ از ۲٬۳۴۰'], ['RUN-305 نتیجه', 'نامعلوم (صفر نیست)']], export: 'زیرمجموعهٔ محدود برابر خروجی کامل نیست' },
      { id: 'REP-HIS', name: 'وضعیت تاریخی (As-Of)', grain: 'رویداد/اسنپ‌شات', basis: 'hist', time: 'تاریخ برش و منطقهٔ زمانی', unit: 'طبق رویداد', src: 'فقط تاریخچهٔ بازیابی‌پذیر', fresh: 'stale', cov: 'partial', rec: 'نامعلوم صریح', rows: [['مانده در برش ۱۴۰۵/۰۶/۳۱', 'نامعلوم (UNKNOWN) — شواهد کافی نیست']], export: 'نیازمند اثبات بازسازی' },
      { id: 'REP-SR', name: 'آمادگی تسویه', grain: 'اعتبار ثبت‌شده/تعهد', basis: 'snap', time: 'اسنپ‌شات', unit: 'تومان', src: 'اعتبارهای ثبت‌شده', fresh: 'ok', cov: 'ok', rec: 'آمادگی ≠ تسویه پرداخت‌شده', rows: [['آمادهٔ بررسی تسویه', '۴٬۸۰۰٬۰۰۰ تومان'], ['تسویه پرداخت‌شده', 'در این رابط وجود ندارد']], export: 'حداقل اطلاعات بانکی', note: 'اجرای انتقال بانکی در این رابط وجود ندارد.' }
    ],
    audit: [
      { id: 'AU-1', at: 'امروز ۰۹:۴۰', actor: 'سارا مرادی', kind: 'تولید پیش‌نمایش اجرا', inv: '—', cs: '—', ev: '—', amt: '—', ba: 'ایجاد فراداده اجرا RUN-311', reason: 'محاسبهٔ ماهانه', rev: '—', tx: '—', key: '—', run: 'RUN-311', res: 'موفق', corr: 'C-7701' },
      { id: 'AU-2', at: '۱۴۰۵/۰۷/۱۵ ۱۰:۱۰', actor: 'امیر صادقی', kind: 'تأیید اجرا', inv: '—', cs: '—', ev: '—', amt: '—', ba: 'در انتظار تأیید ← تأییدشده (قفل ثبت شد)', reason: 'بررسی نمونه', rev: 'تأییدشده', tx: '—', key: '—', run: 'RUN-309', res: 'موفق', corr: 'C-7690' },
      { id: 'AU-3', at: '۱۴۰۵/۰۷/۱۴', actor: 'سارا مرادی', kind: 'رد مرحلهٔ پرداخت', inv: 'INV-48101', cs: 'CASE-7601', ev: 'EV-9801 v1', amt: '۶٬۰۰۰٬۰۰۰ تومان', ba: 'در انتظار ← رد شد (تأییدهای قبلی حفظ)', reason: 'رسید نامرتبط', rev: 'رد شده', tx: '—', key: '—', run: '—', res: 'موفق', corr: 'C-7688' },
      { id: 'AU-4', at: 'دیروز ۱۷:۳۰', actor: 'سارا مرادی', kind: 'ثبت اجرا (APPLY)', inv: '—', cs: '—', ev: '—', amt: '—', ba: 'تأییدشده ← نتیجه نامعلوم', reason: '—', rev: '—', tx: 'ثبت نشده', key: 'RUN-305|…', run: 'RUN-305', res: 'نامعلوم', corr: 'C-7699' },
      { id: 'AU-5', at: '۱۴۰۵/۰۷/۰۹ ۱۷:۲۰', actor: 'امیر صادقی', kind: 'ثبت تراکنش استرداد', inv: 'INV-47950', cs: 'CASE-7405', ev: 'BNK-77412', amt: '۴٬۰۰۰٬۰۰۰ تومان', ba: 'خالص وصول کاهش یافت', reason: 'استرداد جزئی', rev: '—', tx: 'T-9007', key: 'RF-33|INV-47950|refund', run: '—', res: 'موفق', corr: 'C-7655' },
      { id: 'AU-6', at: '۱۴۰۵/۰۷/۰۲ ۱۶:۱۵', actor: 'سیستم (معکوس‌سازی لغو)', kind: 'معکوس‌سازی', inv: 'INV-48033', cs: '—', ev: '—', amt: '۱٬۵۰۰٬۰۰۰ تومان', ba: 'T-9004 با T-9005 جبران شد (حذف نشد)', reason: 'لغو فاکتور', rev: '—', tx: 'T-9005', key: 'REV|T-9004', run: '—', res: 'موفق', corr: 'C-7620' }
    ],
    /* conceptual permissions (NOT WordPress capabilities; target contract). cur = what current code is known to gate (F06) */
    perms: [
      { k: 'view', concept: 'view_finance_queue / view_scoped_financial_data', write: false, cur: 'فعلی: سمت/نقش مالی (view)', note: 'دیدن صف و داده در دامنهٔ مجاز' },
      { k: 'review', concept: 'review_payment_evidence', write: false, cur: 'تعریف جدا نشده', note: 'مشاهدهٔ مدرک؛ دانلود محافظت مستقل' },
      { k: 'approve', concept: 'approve_financial_stage', write: true, cur: 'فعلی: sn_approve_payment (کد)', note: 'تأیید مرحلهٔ جاری' },
      { k: 'reject', concept: 'reject_financial_stage', write: true, cur: 'فعلی: sn_reject_payment (کد)', note: 'رد با دلیل' },
      { k: 'refund', concept: 'view_refunds / process_refund', write: true, cur: 'اجرای بانکی وجود ندارد', note: 'مشروط به OPD-04', cond: 'OPD-04' },
      { k: 'ledger', concept: 'view_ledger / post_ledger_entry', write: true, cur: 'تعدیل دستی: فقط مدیر سیستم', note: 'خواندن و نوشتن جدا', onlyAdmin: true },
      { k: 'runapprove', concept: 'view_finance_runs / approve_finance_run', write: true, cur: 'فعلی: همان دروازهٔ مشاهده (F06)', note: 'مشروط به OPD-08 (تفکیک وظیفه)', cond: 'OPD-08', f06: true },
      { k: 'post', concept: 'execute_posting', write: true, cur: 'فعلی: همان دروازهٔ مشاهده (F06)', note: 'اجرای ثبت روی snapshot تأییدشده', f06: true },
      { k: 'reconcile', concept: 'reconcile_financial_data', write: true, cur: 'تعریف جدا نشده', note: 'بررسی جدا از اصلاح؛ اصلاح مجزا' },
      { k: 'export', concept: 'view_finance_reports / export_finance_reports', write: true, cur: 'اجرا نشده', note: 'خروجی: اختیار جدا و مشروط', cond: 'export' },
      { k: 'audit', concept: 'view_finance_audit', write: false, cur: 'تعریف جدا نشده', note: 'حداقل فیلد لازم' }
    ],
    maint: [
      { id: 'M-1', name: 'بازمحاسبهٔ قدیمی کیف پول (recalculate)', fx: 'ممکن است اثر مالی/بازنویسی مانده داشته باشد', auth: 'امروز: دروازهٔ مشاهده یا مدیر (F06) — هدف: اختیار جدا', why: 'اختیار خواندن مجوز نوشتن نیست.' },
      { id: 'M-2', name: 'پرکردن تاریخی ماتریس (backfill)', fx: 'ممکن است اعتبارهای گذشتهٔ مفقود بسازد', auth: 'sn_manage_wallets یا مدیر سیستم', why: 'حفاظت از تاریخچه و استحقاق.' },
      { id: 'M-3', name: 'تعدیل دستی دفتر کل', fx: 'ثبت تراکنش جدید (نه ویرایش گذشته)', auth: 'فقط مدیر سیستم', why: 'اختیار post_ledger_entry به مالی داده نشده است.' },
      { id: 'M-4', name: 'فعال‌سازی ثبت (پرچم سراسری)', fx: 'اجازهٔ APPLY برای همهٔ اجراها', auth: 'حوزهٔ انتشار مدیر مجاز', why: 'در دامنهٔ روزانهٔ بررسی نیست.' },
      { id: 'M-5', name: 'تشخیص آمادگی/یتیم (فقط خواندنی)', fx: 'بدون اثر؛ فقط گزارش', auth: 'مشاهده', why: 'تشخیص خواندنی است و چیزی را اصلاح نمی‌کند.', readOnly: true }
    ]
  };
})();
