/* HR — mock data for the design prototype (SN-205). NOT business authority: every name/ID/number is fictional.
   HR ROLE RUNTIME IS NOT LIVE VERIFIED (HR-G01). Product boundaries: HR-PRODUCT-SPEC.md + GATE-0-PRODUCT-INVARIANTS.md.
   Nothing here is saved, sent or executed. Person ≠ Profile ≠ WordPress User ≠ Role ≠ Position ≠ Hierarchy assignment. */
(function () {
  'use strict';
  var H = function (from, to, parent, pos, applied, actor, src, state) { return { from: from, to: to, parent: parent, pos: pos, applied: applied, actor: actor, src: src, state: state || 'known' }; };
  var U = function (note) { return H(null, null, null, null, null, null, note || 'ثبت نشده', 'unknown'); };

  var D = window.HR = {
    user: { name: 'الهام بهرامی', id: '۱۷۰۰۳', pos: 'منابع انسانی' },
    freshness: { now: '۱۴:۲۰', evaluated: 'امروز ۱۴:۲۰ (+۰۳:۳۰)', stale: 'دیروز ۱۷:۴۵' },
    positions: [
      { id: 'deputy', label: 'معاون فروش', level: 0, role: 'نقش عملیاتی معاون', n: 1 }, { id: 'manager', label: 'مدیر فروش', level: 1, role: 'نقش عملیاتی مدیر', n: 3 }, { id: 'senior', label: 'سرپرست ارشد', level: 2, role: 'نقش عملیاتی سرپرست ارشد', n: 1 },
      { id: 'sup', label: 'سرپرست', level: 3, role: 'نقش عملیاتی سرپرست', n: 4 }, { id: 'seller', label: 'فروشنده', level: 4, role: 'نقش عملیاتی فروشنده', n: 8 }, { id: 'hr', label: 'منابع انسانی', level: null, role: 'نقش عملیاتی HR', n: 1 }
    ],
    /* ---------- Workforce profiles. Linkage states: ok · partial · missing · conflict. hist = effective-interval history (newest first). ---------- */
    staff: [
      { id: 'HP-100', name: 'علیرضا شکوهی', pos: 'deputy', lvl: '۰', parent: null, unit: 'مدیریت فروش', emp: 'active', user: '۴۱۰۰', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۱۲···۱۰۰۱', conf: [], hist: [H('۱۴۰۴/۰۱/۰۱', null, null, 'معاون فروش', '۱۴۰۴/۰۱/۰۱', 'سیستم', 'ایجاد پروفایل')] },
      { id: 'HP-110', name: 'فرهاد نجفی', pos: 'manager', lvl: '۱', parent: 'HP-100', unit: 'تیم شمال', emp: 'active', user: '۴۱۱۰', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۱۲···۱۱۱۰', conf: [], hist: [H('۱۴۰۴/۰۱/۰۱', null, 'HP-100', 'مدیر فروش', '۱۴۰۴/۰۱/۰۱', 'سیستم', 'ایجاد پروفایل')] },
      { id: 'HP-120', name: 'مهسا رضوی', pos: 'manager', lvl: '۱', parent: 'HP-100', unit: 'تیم جنوب', emp: 'active', user: '۴۱۲۰', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۱۲···۱۲۲۰', conf: [], hist: [H('۱۴۰۴/۰۱/۰۱', null, 'HP-100', 'مدیر فروش', '۱۴۰۴/۰۱/۰۱', 'سیستم', 'ایجاد پروفایل')] },
      { id: 'HP-130', name: 'کیان عباسی', pos: 'manager', lvl: '۱', parent: 'HP-100', unit: 'تیم غرب', emp: 'inactive', user: '۴۱۳۰', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۱۲···۱۳۳۰', conf: ['inactiveMgr'], hist: [H('۱۴۰۵/۰۶/۲۰', null, 'HP-100', 'مدیر فروش', '۱۴۰۵/۰۶/۲۰', 'الهام بهرامی', 'ویرایش مستقیم · غیرفعال‌سازی'), H('۱۴۰۴/۰۱/۰۱', '۱۴۰۵/۰۶/۲۰', 'HP-100', 'مدیر فروش', '۱۴۰۴/۰۱/۰۱', 'سیستم', 'ایجاد پروفایل')] },
      { id: 'HP-210', name: 'آرش یگانه', pos: 'sup', lvl: '۳', parent: 'HP-110', unit: 'تیم شمال ۱', emp: 'active', user: '۴۲۱۰', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۱۲···۲۲۱۰', conf: [], hist: [H('۱۴۰۴/۰۴/۱۰', null, 'HP-110', 'سرپرست', '۱۴۰۴/۰۴/۱۰', 'الهام بهرامی', 'درخواست R-480'), H('۱۴۰۴/۰۱/۰۱', '۱۴۰۴/۰۴/۱۰', 'HP-120', 'سرپرست', '۱۴۰۴/۰۱/۰۱', 'سیستم', 'ایجاد پروفایل')] },
      { id: 'HP-220', name: 'نیلوفر حسینی', pos: 'sup', lvl: '۳', parent: 'HP-130', unit: 'تیم غرب ۱', emp: 'active', user: '۴۲۲۰', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۱۲···۲۲۲۰', conf: ['inactiveMgr'], hist: [H('۱۴۰۴/۰۱/۰۱', null, 'HP-130', 'سرپرست', '۱۴۰۴/۰۱/۰۱', 'سیستم', 'ایجاد پروفایل')] },
      { id: 'HP-301', name: 'مریم احمدی', pos: 'seller', lvl: '۴', parent: 'HP-210', unit: 'تیم شمال ۱', emp: 'active', user: '۴۳۰۱', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۱۹···۳۰۰۱', conf: [], open: { leads: 22, inv: 2, cust: 5, tasks: 3, verified: true }, hist: [H('۱۴۰۵/۰۲/۱۵', null, 'HP-210', 'فروشنده', '۱۴۰۵/۰۲/۱۵', 'الهام بهرامی', 'درخواست R-501'), H('۱۴۰۴/۰۸/۰۱', '۱۴۰۵/۰۲/۱۵', 'HP-120', 'فروشنده', '۱۴۰۴/۰۸/۰۱', 'سیستم', 'ایجاد پروفایل')] },
      { id: 'HP-302', name: 'زهرا کریمی', pos: 'seller', lvl: '۴', parent: 'HP-210', unit: 'تیم شمال ۱', emp: 'active', user: '۴۳۰۲', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۱۹···۳۰۰۲', conf: [], open: { leads: 14, inv: 1, cust: 3, tasks: 0, verified: true }, hist: [H('۱۴۰۴/۰۹/۱۰', null, 'HP-210', 'فروشنده', '۱۴۰۴/۰۹/۱۰', 'سیستم', 'ایجاد پروفایل')] },
      { id: 'HP-303', name: 'امین توکلی', pos: 'seller', lvl: '۴', parent: 'HP-120', unit: 'تیم جنوب', emp: 'active', user: '۴۳۰۳', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۱۹···۳۰۰۳', conf: ['histGap'], open: { leads: 31, inv: 4, cust: 9, tasks: 5, verified: true }, hist: [H('۱۴۰۵/۰۳/۰۱', null, 'HP-120', 'نامشخص', '۱۴۰۵/۰۳/۰۱', 'الهام بهرامی', 'ویرایش مستقیم', 'incomplete'), U('پیش از ۱۴۰۵/۰۳/۰۱: مدیر و سمت ثبت نشده')] },
      { id: 'HP-304', name: 'سارا مرادی', pos: 'seller', lvl: '۴', parent: 'HP-220', unit: 'تیم غرب ۱', emp: 'active', user: '۴۳۰۴', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۱۹···۳۰۰۴', conf: ['termOpen', 'inactiveMgr'], open: { leads: 18, inv: 3, cust: 7, tasks: 4, verified: true }, hist: [H('۱۴۰۴/۱۰/۰۱', null, 'HP-220', 'فروشنده', '۱۴۰۴/۱۰/۰۱', 'سیستم', 'ایجاد پروفایل')] },
      { id: 'HP-305', name: 'پویا نادری', pos: 'seller', lvl: '۴', parent: 'HP-210', unit: 'تیم شمال ۱', emp: 'active', user: '۴۳۰۵', lk: ['partial', 'conflict'], role: 'ok', mob: '۰۹۳۵···۳۰۰۵', conf: ['dupProfile'], dup: 'HP-305b', hist: [H('۱۴۰۵/۰۱/۲۰', null, 'HP-210', 'فروشنده', '۱۴۰۵/۰۱/۲۰', 'سیستم', 'ایجاد پروفایل')] },
      { id: 'HP-306', name: 'ندا سلیمی', pos: 'seller', lvl: '۴', parent: 'HP-110', unit: 'تیم شمال', emp: 'active', user: null, lk: ['partial', 'missing'], role: 'nouser', mob: '۰۹۲۱···۳۰۰۶', conf: ['noUser'], hist: [H('۱۴۰۵/۰۶/۰۲', null, 'HP-110', 'فروشنده', '۱۴۰۵/۰۶/۰۲', 'الهام بهرامی', 'ورود نیرو (ناتمام)')] },
      { id: 'HP-307', name: 'بهنام صالحی', pos: 'seller', lvl: '۴', parent: 'HP-120', unit: 'تیم جنوب', emp: 'active', user: '۴۳۰۷', lk: ['partial', 'ok'], role: 'mismatch', mob: '۰۹۱۹···۳۰۰۷', conf: ['roleMismatch'], hist: [H('۱۴۰۴/۱۱/۰۵', null, 'HP-120', 'فروشنده', '۱۴۰۴/۱۱/۰۵', 'سیستم', 'ایجاد پروفایل')] },
      { id: 'HP-308', name: 'لیلا فرخی', pos: 'seller', lvl: '۴', parent: null, unit: '—', emp: 'active', user: '۴۳۰۸', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۳۰···۳۰۰۸', conf: ['noParent'], hist: [U('بدون سابقه مدیر')] },
      { id: 'HP-309', name: 'حامد زارعی', pos: 'seller', lvl: '۴', parent: 'HP-110', unit: 'تیم شمال', emp: 'active', user: '۴۳۰۹', lk: ['partial', 'ok'], role: 'partial', mob: '۰۹۱۴···۳۰۰۹', conf: ['accessPartial'], hist: [H('۱۴۰۵/۰۷/۱۵', null, 'HP-110', 'فروشنده', '۱۴۰۵/۰۷/۱۵', 'الهام بهرامی', 'تغییر سمت (دسترسی ناقص اعمال شد)')] },
      { id: 'HP-311', name: 'کامران ربیعی', pos: 'seller', lvl: '۴', parent: 'HP-110', unit: 'تیم شمال', emp: 'active', user: '۴۳۱۱', lk: ['partial', 'ok'], role: 'ok', mob: '۰۹۱۲···۳۱۱۱', conf: [], open: { leads: 0, inv: 0, cust: 0, tasks: 0, verified: true }, hist: [H('۱۴۰۴/۱۲/۰۱', null, 'HP-110', 'فروشنده', '۱۴۰۴/۱۲/۰۱', 'سیستم', 'ایجاد پروفایل')] }
    ],
    /* ---------- HR requests (internal status IDs preserved: pending_review · approved_step · pending_hr · approved(+applied_at) · rejected · failed) ---------- */
    requests: [
      { id: 'R-501', type: 'transfer', from: 'HP-210', subj: 'HP-301', by: 'مدیر مهسا رضوی', reason: 'نیاز تیم به ظرفیت فروش', to: 'HP-120', st: 'pending_review', cur: 'سرپرست ارشد کاوه محمدی', next: 'منابع انسانی', chain: [['درخواست‌دهنده', 'done', 'مدیر مهسا رضوی · ۱۴۰۵/۰۷/۱۵'], ['بررسی سرپرست ارشد', 'cur', 'کاوه محمدی'], ['منابع انسانی', 'skip', 'اعمال نهایی']], eff: null },
      { id: 'R-502', type: 'transfer', from: 'HP-210', subj: 'HP-302', by: 'مدیر فرهاد نجفی', reason: 'ادغام تیم‌های هم‌منطقه', to: 'HP-120', st: 'pending_hr', cur: 'منابع انسانی', next: '—', chain: [['درخواست‌دهنده', 'done', 'مدیر فرهاد نجفی · ۱۴۰۵/۰۷/۱۲'], ['تأیید مرحله‌ای', 'done', 'سرپرست ارشد کاوه محمدی · ۱۴۰۵/۰۷/۱۳'], ['منابع انسانی', 'cur', 'اعمال نهایی']], eff: null },
      { id: 'R-503', type: 'transfer', from: 'HP-120', subj: 'HP-303', by: 'مدیر مهسا رضوی', reason: 'انتقال به تیم غرب', to: 'HP-130', st: 'pending_hr', cur: 'منابع انسانی', next: '—', chain: [['درخواست‌دهنده', 'done', 'مدیر مهسا رضوی · ۱۴۰۵/۰۷/۱۰'], ['تأیید مرحله‌ای', 'done', 'سرپرست ارشد · ۱۴۰۵/۰۷/۱۱'], ['منابع انسانی', 'cur', 'اعمال نهایی']], eff: null, targetInactive: true },
      { id: 'R-504', type: 'terminate', subj: 'HP-304', by: 'سرپرست نیلوفر حسینی', reason: 'پایان قرارداد', to: null, st: 'pending_hr', cur: 'منابع انسانی', next: '—', chain: [['درخواست‌دهنده', 'done', 'سرپرست نیلوفر حسینی · ۱۴۰۵/۰۷/۱۴'], ['تأیید مرحله‌ای', 'done', 'مدیر کیان عباسی (غیرفعال؛ مرحله ثبت‌شده)'], ['منابع انسانی', 'cur', 'اعمال نهایی']], eff: '۱۴۰۵/۰۷/۳۰' },
      { id: 'R-505', type: 'transfer', from: 'HP-120', subj: 'HP-210', by: 'مدیر فرهاد نجفی', reason: 'بازآرایی شاخه', to: 'HP-110', st: 'approved', cur: '—', next: '—', chain: [['درخواست‌دهنده', 'done', 'مدیر فرهاد نجفی'], ['تأیید مرحله‌ای', 'done', 'کاوه محمدی'], ['منابع انسانی', 'done', 'الهام بهرامی · اعمال شد']], eff: null, appliedAt: '۱۴۰۴/۰۴/۱۰ · ۱۱:۲۰', actual: { before: 'مدیر مهسا رضوی', after: 'مدیر فرهاد نجفی', ok: true } },
      { id: 'R-506', type: 'transfer', from: 'HP-110', subj: 'HP-309', by: 'مدیر فرهاد نجفی', reason: 'ارتقا به سرپرست آزمایشی', to: 'HP-210', st: 'failed', cur: '—', next: '—', chain: [['درخواست‌دهنده', 'done', 'مدیر فرهاد نجفی'], ['تأیید مرحله‌ای', 'done', 'کاوه محمدی'], ['منابع انسانی', 'rejected', 'اعمال ناموفق']], eff: null, fail: 'ثبت بازه جدید پس از بستن بازه فعلی ناموفق بود (نتیجه نامعلوم)', actual: { before: 'مدیر فرهاد نجفی', after: 'نامعلوم', ok: false } },
      { id: 'R-507', type: 'terminate', subj: 'HP-311', by: 'مدیر فرهاد نجفی', reason: 'درخواست شخصی', to: null, st: 'rejected', cur: '—', next: '—', chain: [['درخواست‌دهنده', 'done', 'مدیر فرهاد نجفی'], ['تأیید مرحله‌ای', 'rejected', 'کاوه محمدی · رد با دلیل']], eff: null, rejNote: 'جایگزین تعیین نشده است' },
      { id: 'R-508', type: 'transfer', from: 'HP-120', subj: 'HP-305', by: 'سرپرست آرش یگانه', reason: 'تغییر شیفت', to: 'HP-110', st: 'pending_review', cur: 'مدیر فرهاد نجفی', next: 'منابع انسانی', chain: [['درخواست‌دهنده', 'done', 'سرپرست آرش یگانه'], ['بررسی مدیر', 'cur', 'فرهاد نجفی'], ['منابع انسانی', 'skip', 'اعمال نهایی']], eff: null, changed: 'مدیر فعلی فرد پس از ثبت درخواست تغییر کرده است (قبلاً HP-120)' },
      { id: 'R-509', type: 'transfer', from: 'HP-120', subj: 'HP-307', by: 'فروشنده خارج از شاخه', reason: '—', to: 'HP-210', st: 'pending_review', cur: 'مدیر مهسا رضوی', next: 'منابع انسانی', chain: [['درخواست‌دهنده', 'done', 'خارج از محدوده فرد'], ['بررسی مدیر', 'cur', 'مهسا رضوی'], ['منابع انسانی', 'skip', 'اعمال نهایی']], eff: null, oos: true },
      { id: 'R-510', type: 'terminate', subj: 'HP-302', by: 'مدیر فرهاد نجفی', reason: 'مهاجرت', to: null, st: 'approved_step', cur: 'سرپرست ارشد کاوه محمدی', next: 'منابع انسانی', chain: [['درخواست‌دهنده', 'done', 'مدیر فرهاد نجفی'], ['تأیید مرحله‌ای', 'done', 'مدیر فرهاد نجفی (مرحله اول)'], ['بررسی سرپرست ارشد', 'cur', 'کاوه محمدی'], ['منابع انسانی', 'skip', 'اعمال نهایی']], eff: null }
    ],
    /* ---------- Access: permission sources. src = position | role | direct | inherit | none. Rows are product-permission concepts, not WP capability names. ---------- */
    perms: [
      { k: 'inv', label: 'مشاهده فاکتورهای محدوده', sens: false }, { k: 'manInv', label: 'ثبت فاکتور دستی', sens: true }, { k: 'extra', label: 'شماره اضافه', sens: true },
      { k: 'team', label: 'مشاهده گزارش تیم', sens: false }, { k: 'step', label: 'تأیید مرحله درخواست HR', sens: true }, { k: 'assign', label: 'تخصیص مستقیم منبع', sens: true }
    ],
    access: {
      'HP-301': { intended: 'seller', rows: { inv: ['position', 'allow'], manInv: ['inherit', 'deny'], extra: ['direct', 'allow', 'استثنای مستقیم با تأیید مدیر ۱۴۰۵/۰۵'], team: ['none', 'deny'], step: ['none', 'deny'], assign: ['none', 'deny'] } },
      'HP-307': { intended: 'seller', actualRole: 'نقش عملیاتی سرپرست (قدیمی)', rows: { inv: ['position', 'allow'], manInv: ['direct', 'deny', 'مرور درخواست ۱۴۰۵/۰۵'], extra: ['inherit', 'allow'], team: ['role', 'allow', 'نقش سرپرست باقی مانده'], step: ['role', 'allow', 'نقش سرپرست باقی مانده'], assign: ['none', 'deny'] } },
      'HP-309': { intended: 'seller', actualRole: 'نقش فروشنده (اعمال ناقص)', rows: { inv: ['position', 'allow'], manInv: ['inherit', 'deny'], extra: ['inherit', 'deny'], team: ['none', 'deny'], step: ['none', 'deny'], assign: ['none', 'deny'] }, partial: 'اعمال دسترسی ناقص ماند: دو مجوز مورد انتظار اعمال نشد' },
      'default': { rows: { inv: ['position', 'allow'], manInv: ['inherit', 'deny'], extra: ['inherit', 'deny'], team: ['none', 'deny'], step: ['none', 'deny'], assign: ['none', 'deny'] } }
    },
    /* ---------- Compensation (field-permission sensitive; HR runtime NOT LIVE VERIFIED). Values fictional. ---------- */
    comp: {
      'HP-301': { base: '۳۲٬۰۰۰٬۰۰۰', cur: 'IRT', com: true, rule: 'CR-12', mode: 'ارجاع قاعده', periods: [{ from: '۱۴۰۵/۰۴/۰۱', to: null, base: '۳۲٬۰۰۰٬۰۰۰', reason: 'بازبینی سالانه', actor: 'الهام بهرامی', applied: '۱۴۰۵/۰۴/۰۲', before: '۲۸٬۰۰۰٬۰۰۰' }, { from: '۱۴۰۴/۰۴/۰۱', to: '۱۴۰۵/۰۳/۳۱', base: '۲۸٬۰۰۰٬۰۰۰', reason: 'استخدام', actor: 'الهام بهرامی', applied: '۱۴۰۴/۰۴/۰۱', before: '—' }] },
      'HP-302': { base: '۲۸٬۰۰۰٬۰۰۰', cur: 'IRT', com: true, rule: 'CR-12', mode: 'ارجاع قاعده', periods: [{ from: '۱۴۰۴/۰۹/۱۰', to: null, base: '۲۸٬۰۰۰٬۰۰۰', reason: 'استخدام', actor: 'الهام بهرامی', applied: '۱۴۰۴/۰۹/۱۰', before: '—' }] },
      'HP-303': { base: '۳۰٬۰۰۰٬۰۰۰', cur: 'IRT', com: true, rule: 'CR-14', mode: 'جایگزین فردی', periods: [{ from: '۱۴۰۵/۰۳/۰۱', to: null, base: '۳۰٬۰۰۰٬۰۰۰', reason: 'تغییر تیم', actor: 'الهام بهرامی', applied: '۱۴۰۵/۰۳/۰۵', before: '۲۶٬۰۰۰٬۰۰۰' }, { from: '۱۴۰۴/۰۸/۰۱', to: '۱۴۰۵/۰۲/۳۱', base: '۲۶٬۰۰۰٬۰۰۰', reason: '—', actor: 'نامشخص', applied: null, before: '—', gap: true }], overlap: 'همپوشانی بازه ۱۴۰۵/۰۲/۲۰ تا ۱۴۰۵/۰۲/۳۱ با بازه قبلی گزارش شده' },
      'HP-304': { base: '۲۹٬۰۰۰٬۰۰۰', cur: 'IRT', com: false, rule: null, mode: '—', periods: [{ from: '۱۴۰۴/۱۰/۰۱', to: null, base: '۲۹٬۰۰۰٬۰۰۰', reason: 'استخدام', actor: 'الهام بهرامی', applied: '۱۴۰۴/۱۰/۰۱', before: '—' }] },
      'HP-306': { base: null, cur: null, com: false, rule: null, mode: '—', periods: [] }
    },
    /* ---------- Exceptions / Audit. Classes follow Product Spec §15. ---------- */
    exc: [
      { id: 'X1', cls: 'hier', tone: 'red', title: 'چرخه در سلسله‌مراتب فعلی (HP-141 ↔ HP-142)', subj: ['hierarchy', 'HP-141 / HP-142', null], owner: 'منابع انسانی (ساختار)', st: 'open', impact: 'نمایش سلسله‌مراتب و تأییدهای مرحله‌ای این شاخه ممکن است ناقص باشد', allowed: ['خواندن چرخه و وضعیت والد', 'پیشنهاد اصلاح والد فعلی با بازه معتبر'], notAllowed: ['بازنویسی سلسله‌مراتب گذشته'], proof: ['بازه معتبر و تاریخچه ثبت شود', 'دامنه فعلی و چرخه‌نبودن اثبات شود'] },
      { id: 'X2', cls: 'inactiveMgr', tone: 'orange', title: 'مدیر غیرفعال با نیروهای فعال (کیان عباسی)', subj: ['staff', 'HP-130', 'HP-130'], owner: 'منابع انسانی + فروش', st: 'open', impact: '۲ نفر فعال زیر مدیر غیرفعال؛ مسئول بعدی هماهنگی ثبت نشده', allowed: ['بررسی شاخه‌های متأثر', 'پیشنهاد ساختار مجاز'], notAllowed: ['جانشین یا انتقال مسئولیت خودکار'], proof: ['والد فعلی تأییدشده', 'تحویل کار (OPD-05) مشخص شود'] },
      { id: 'X3', cls: 'pending', tone: 'amber', title: 'درخواست‌های منتظر بررسی (۴) — سن فقط از زمان ثبت', subj: ['request', 'R-501', null], owner: 'بررسی‌کننده فعلی', st: 'awaiting', impact: 'تأیید مرحله‌ای ≠ اعمال نهایی', allowed: ['مشاهده بررسی‌کننده فعلی/بعدی', 'بررسی در صورت مجاز بودن'], notAllowed: ['دستور تشدید یا SLA'], proof: ['اثبات تأیید مرحله‌ای یا اعمال نهایی جدا'] },
      { id: 'X4', cls: 'failed', tone: 'red', title: 'اعمال ناموفق درخواست R-506', subj: ['request', 'R-506', null], owner: 'منابع انسانی / سرویس اعمال', st: 'open', impact: 'اثر واقعی نامعلوم: بازه فعلی بسته شده ولی بازه جدید ثبت نشده', allowed: ['خواندن اثر واقعی و تاریخچه', 'سیاست بازیابی مصوب (تعریف نشده)'], notAllowed: ['اعمال دوباره کور'], proof: ['وضعیت قبل/بعد قطعی و تطبیق‌شده'] },
      { id: 'X5', cls: 'dup', tone: 'orange', title: 'دو پروفایل برای یک حساب (HP-305 و HP-305b)', subj: ['staff', 'HP-305', 'HP-305'], owner: 'مالک هویت', st: 'open', impact: 'تاریخچه و دسترسی ممکن است به دو پروفایل تقسیم شود', allowed: ['مقایسه شناسه‌های بومی و نگاشت'], notAllowed: ['ادغام مخرب کاربر/پروفایل'], proof: ['پیوند پایدار و تاریخچه حفظ‌شده'] },
      { id: 'X6', cls: 'noUser', tone: 'amber', title: 'پروفایل بدون حساب کاربری (ندا سلیمی)', subj: ['staff', 'HP-306', 'HP-306'], owner: 'منابع انسانی / مالک حساب فنی', st: 'open', impact: 'ورود نیرو ناتمام؛ دسترسی اعمال نشده', allowed: ['تطبیق هویت و پیوند مجاز'], notAllowed: ['ساخت کاربر ممتاز یا اعتبارنامه از اینجا'], proof: ['پروفایل و کاربر پیوند‌خورده با شناسه'] },
      { id: 'X7', cls: 'roleMismatch', tone: 'orange', title: 'ناهمخوانی نقش و سمت (بهنام صالحی)', subj: ['staff', 'HP-307', 'HP-307'], owner: 'مالک دسترسی', st: 'open', impact: 'نقش سرپرست قدیمی باقی مانده؛ مجوزهای اضافه فعال است', allowed: ['مقایسه دسترسی مؤثر و نگاشت مورد انتظار'], notAllowed: ['بازنشانی کامل یا نگاشت اجباری نقش'], proof: ['دلتای دقیق و تاریخچه'] },
      { id: 'X8', cls: 'termOpen', tone: 'red', title: 'پایان همکاری با کار باز (سارا مرادی)', subj: ['staff', 'HP-304', 'HP-304'], owner: 'منابع انسانی + فروش/مالی', st: 'open', impact: '۱۸ لید، ۳ فاکتور، ۷ مشتری، ۴ وظیفه باز؛ گیرنده تحویل نامشخص (OPD-05)', allowed: ['فهرست اثر و مسئول بعدی'], notAllowed: ['پرونده بدون مسئول', 'حذف مالی'], proof: ['مسئول نام‌برده برای هر کار باز'] },
      { id: 'X9', cls: 'oos', tone: 'slate', title: 'درخواست خارج از محدوده (R-509)', subj: ['request', 'R-509', null], owner: 'دارنده درخواست', st: 'awaiting', impact: 'درخواست‌دهنده مجاز به این فرد نیست', allowed: ['رد/ثبت تعارض با دلیل دامنه'], notAllowed: ['عبور با رتبه بالاتر'], proof: ['فرد و بررسی‌کننده مجاز اثبات شود'] },
      { id: 'X10', cls: 'accessPartial', tone: 'orange', title: 'اعمال دسترسی ناقص (حامد زارعی)', subj: ['staff', 'HP-309', 'HP-309'], owner: 'سرویس دسترسی', st: 'open', impact: 'مجوزهای مورد انتظار با واقعی یکی نیست', allowed: ['مقایسه مورد انتظار و واقعی'], notAllowed: ['تغییر دلخواه نقش در WP Admin'], proof: ['دلتای اعمال‌شده و ممیزی دقیق'] },
      { id: 'X11', cls: 'histGap', tone: 'slate', title: 'شکاف تاریخچه انتساب (امین توکلی)', subj: ['staff', 'HP-303', 'HP-303'], owner: 'مالک تاریخچه/دامنه', st: 'awaiting', impact: 'مدیر و سمت پیش از ۱۴۰۵/۰۳/۰۱ نامشخص (UNKNOWN)', allowed: ['نمایش نامشخص و محدود تفسیر'], notAllowed: ['استنتاج گذشته از مدیر فعلی'], proof: ['زمان یا snapshot معتبر'] }
    ],
    audit: [
      { id: 'A9', at: 'امروز ۱۳:۱۰', actor: 'الهام بهرامی', act: 'تغییر سمت', subj: 'HP-309', req: '—', before: 'سمت: فروشنده', after: 'سمت: فروشنده (دسترسی ناقص)', reason: 'اصلاح نگاشت', chain: '—', eff: 'همان لحظه', applied: 'امروز ۱۳:۱۰', res: 'partial', corr: 'hr-7c11' },
      { id: 'A8', at: 'امروز ۱۱:۴۰', actor: 'الهام بهرامی', act: 'اعمال درخواست انتقال', subj: 'HP-309', req: 'R-506', before: 'مدیر: فرهاد نجفی', after: 'نامعلوم', reason: 'ارتقا آزمایشی', chain: 'درخواست‌دهنده ← تأیید مرحله‌ای ← HR', eff: 'ثبت نشده', applied: '—', res: 'failed', corr: 'hr-7a02' },
      { id: 'A7', at: '۱۴۰۵/۰۶/۲۰', actor: 'الهام بهرامی', act: 'غیرفعال‌سازی پروفایل', subj: 'HP-130', req: '—', before: 'وضعیت: فعال', after: 'وضعیت: غیرفعال', reason: 'پایان همکاری مدیر', chain: '—', eff: '۱۴۰۵/۰۶/۲۰', applied: '۱۴۰۵/۰۶/۲۰', res: 'complete', corr: 'hr-6e31' },
      { id: 'A6', at: '۱۴۰۵/۰۶/۰۲', actor: 'الهام بهرامی', act: 'ورود نیرو', subj: 'HP-306', req: '—', before: '—', after: 'پروفایل ایجاد شد؛ حساب پیوند نشد', reason: 'نیروی جدید', chain: '—', eff: '۱۴۰۵/۰۶/۰۲', applied: '۱۴۰۵/۰۶/۰۲', res: 'partial', corr: 'hr-6a12' },
      { id: 'A5', at: '۱۴۰۵/۰۵/۱۰', actor: 'الهام بهرامی', act: 'بازنشانی گذرواژه + پیامک', subj: 'HP-303', req: '—', before: '—', after: 'بازنشانی انجام شد؛ پیامک ارسال نشد', reason: 'درخواست کاربر', chain: '—', eff: 'همان لحظه', applied: '۱۴۰۵/۰۵/۱۰', res: 'partial', corr: 'hr-5d90' },
      { id: 'A4', at: '۱۴۰۵/۰۳/۰۵', actor: 'الهام بهرامی', act: 'ثبت دوره جبران', subj: 'HP-303', req: '—', before: 'پایه: ۲۶٬۰۰۰٬۰۰۰', after: 'پایه: ۳۰٬۰۰۰٬۰۰۰', reason: 'تغییر تیم', chain: '—', eff: '۱۴۰۵/۰۳/۰۱', applied: '۱۴۰۵/۰۳/۰۵', res: 'unknown', corr: '—' }
    ],
    legacy: [
      { src: 'hr-extra (ویرایشگر قدیمی)', map: 'ادغام در پروفایل نیرو', note: 'فیلدها و تاریخچه حفظ می‌شود' },
      { src: 'نقش قدیمی «سرپرست»', map: 'سمت: سرپرست', note: 'هم‌زیستی با نقش جدید ← فقط تشخیص، نه بازنگاشت اجباری' },
      { src: 'کاربران بدون پروفایل (۳)', map: 'نیازمند ورود نیرو', note: 'بدون اصلاح همگانی' },
      { src: 'نگاشت سمت ← نقش عملیاتی', map: 'ساختار و دسترسی ← نگاشت', note: 'نگاشت فعلی حفظ می‌شود' }
    ]
  };
})();
